# Default values for openshift-console.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: quay.io
  repository: openshift/origin-console
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 4.14.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

annotations: {}
labels: {}

podLabels: {}
podAnnotations: {}

podSecurityContext:
  enabled: true
  runAsUser: 1001

securityContext:
  enabled: true
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

extraEnv: {}
#  BRIDGE_K8S_AUTH_BEARER_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6IjRxMTYyMm5PQW9JX1F1RGJYRDFGUGVsVVpfaTE5MmFqamJYZHRzME1VWDQifQ
#  BRIDGE_GRAFANA_PUBLIC_URL: https://grafana.my.company.com
#  BRIDGE_KUBECTL_CLIENT_ID: console
#  BRIDGE_K8S_MODE: off-cluster
#  BRIDGE_K8S_MODE_OFF_CLUSTER_ALERTMANAGER: https://alertmanager.my.company.com
#  BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS: "true"
#  BRIDGE_K8S_MODE_OFF_CLUSTER_THANOS: https://prometheus.my.company.com
#  BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT: https://kube-oidc-proxy.console:443
#  BRIDGE_PLUGINS: "monitoring-plugin=http://console-monitoring:80"

volumes: []
# - name: my-volume
#   mountPath: /foo/bar
#   config:
#     emptyDir: {}

console:
#  dex:
#    host: https://dex.my.company.com
  baseUrl: https://console.my.company.com
  impersonateOpenShift: false
  oidc:
    enabled: false
#    enabled: true
#    issuerUrl: https://dex.my.company.com
#    clientId: console
#    clientSecret: ZXhhbXBsZS1hcHAtc2VjcmV0

rbac:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  beta.kubernetes.io/arch: amd64

tolerations: []

affinity: {}

sidecars: []

serviceAccount:
  create: false
  automountServiceAccountToken: true
  annotations: {}
  name: ""

hostAliases: []
#  - ip: "127.0.0.1"
#    hostnames:
#      - "kubernetes.default.svc"


consolesecret: ZXhhbXBsZS1hcHAtc2VjcmV0
#cookie-encryption-key-file:     "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
#cookie-authentication-key-file: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

args:
- --public-dir=/opt/bridge/static
- -v
- "7"
command:
- /opt/bridge/bin/bridge

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi